### ISSUE TITLE
Images above 1.28 not working

### ISSUE THREAD

**Issue by flyersa** [osism/k8s-capi-images#251]
Hello,

i finally managed to get Magnum CAPI Driver working. Updated images with osism manage image clusterapi.

Only 1.27.15 and 1.28.11 work flawless. Everything above has exact the same error something with calico cni install not working properly (1.29x and 1.30.x):

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  85s                default-scheduler  Successfully assigned kube-system/calico-node-bcsqq to kube-dj61o-gpdjp-r8hlk
  Normal   Pulling    84s                kubelet            Pulling image "docker.io/calico/cni:v3.24.2"
  Normal   Pulled     78s                kubelet            Successfully pulled image "docker.io/calico/cni:v3.24.2" in 5.972s (5.972s including waiting)
  Normal   Created    78s                kubelet            Created container upgrade-ipam
  Normal   Started    78s                kubelet            Started container upgrade-ipam
  Normal   Pulled     44s (x2 over 77s)  kubelet            Container image "docker.io/calico/cni:v3.24.2" already present on machine
  Normal   Created    44s (x2 over 77s)  kubelet            Created container install-cni
  Normal   Started    44s (x2 over 77s)  kubelet            Started container install-cni
  Warning  BackOff    12s                kubelet            Back-off restarting failed container install-cni in pod calico-node-bcsqq_kube-system(1e4183b2-fc13-4fd2-8ca7-313b8cb1c200)


(.install-venv) root@open-mgmt:~# kubectl logs calico-node-bcsqq -n kube-system
Defaulted container "calico-node" out of: calico-node, upgrade-ipam (init), install-cni (init), mount-bpffs (init)
Error from server: no preferred addresses found; known addresses: []

```

clusterctrl components, clusterapi helm and clusterapi components are on latest current versions. I have this in two different environments. Does someone else use the images and can confirm they work?

After digging around a bit that may have something todo with internal IPs and not distributing the FIP or something hmm. will continue digging on it. Not sure if the issue is correct here or belongs somewhere else

**Comment by berendt** [comment]
Jan from SCS did some quick tests yesterday and 1.29 and 1.30 worked. Can you test if it works with CIlium? Jan's guess was that it was due to Calico. Cilium is only used in SCS.

**Comment by flyersa** [comment]
sure will try and report, but i think the magnum stuff only worked with calico so far. Most likely need to sync with vexxhost if it doesnt

**Comment by berendt** [comment]
@flyersa This is resolved?

**Comment by flyersa** [comment]
Yes sorry. Works flawless up to 1.30.x now, 1.31 is not yet supported by vexxhost capi driver
