### ISSUE TITLE
Username and password when boot VM

### ISSUE THREAD

**Issue by jackiechan2331** [osism/k8s-capi-images#253]
When i downloaded your `ubuntu-2204-kube-v1.29.qcow2` image and boot it to VM using `qemu-system-x86_64`, it require username and password to login to the VM. What should i do ?

It appears:

```
Ubuntu 22.04.04 LTS localhost tty1 
localhost login:
```

**Comment by trongnp2000** [comment]
@berendt

**Comment by berendt** [comment]
It is not possible to log in with username/password.

**Comment by jackiechan2331** [comment]
So is there anyway to access the VM?

**Comment by jackiechan2331** [comment]
> It is not possible to log in with username/password.

So is there anyway to access the VM?

**Comment by berendt** [comment]
It looks like there are multiple ways to access the instances managed by CAPI.

* https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/a5cfcd79f479f4dcff5b76e205ea745279a120c3/templates/cluster-template.yaml#L151
* https://github.com/kvaps/kubectl-node-shell
* https://kubernetes.io/docs/tasks/debug/debug-cluster/kubectl-node-debug/
* https://github.com/pabateman/kubectl-nsenter
